# GitLab CI Docker Image
image: node:4.2.2

# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/ onto next steps using artifacts
build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/notimatica-sdk/
  tags:
    - shared
